In [6]:
# Data

company_detail_list = [
      {
          'name': 'Company 1',
          'domain': 'Retail',
          'country': 'United States'
      },
      {
          'name': 'Company 2',
          'domain': 'Technology',
          'country': 'United Kingdom'
      },
      {
          'name': 'Company 3',
          'domain': 'Healthcare',
          'country': 'United States'
      }
  ]

employee_detail_list = [
     {
          'name': 'EMP-0001',
          'first_name': 'John',
          'last_name': 'Doe',
          'full_name': 'John Doe',
          'company': 'Company 1',
          'nationality': 'Australia'
      },
      {
          'name': 'EMP-0002',
          'first_name': 'Tom',
          'last_name': 'Smith',
          'full_name': 'Tom Smith',
          'company': 'Company 2',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0003',
          'first_name': 'Andrew',
          'last_name': 'Sebastian',
          'full_name': 'Andrew Sebastian',
          'company': 'Company 3',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0005',
          'first_name': 'Ying Han',
          'last_name': 'Tan',
          'full_name': 'Ying Han Tan',
          'company': 'Company 1',
          'nationality': 'Australia'
      },
      {
          'name': 'EMP-0015',
          'first_name': 'Kenneth',
          'last_name': 'Ng',
          'full_name': 'Kenneth Ng',
          'company': 'Company 3',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0018',
          'first_name': 'Rubby',
          'last_name': 'Lee',
          'full_name': 'Rubby Lee',
          'company': 'Company 2',
          'nationality': 'Hong Kong'
      },
     {
          'name': 'EMP-0017',
          'first_name': 'Robert',
          'last_name': 'White',
          'full_name': 'Robert White',
          'company': 'Company 1',
          'nationality': 'United Kingdom'
      }
  ]

In [3]:
company_detail_list = [
    {'name': 'Company 1', 'domain': 'Retail', 'country': 'United States'},
    {'name': 'Company 2', 'domain': 'Technology', 'country': 'United Kingdom'},
    {'name': 'Company 3', 'domain': 'Healthcare', 'country': 'United States'}
]

# Extracting company names and sorting in reverse order
sorted_companies = [{'name': company['name']} for company in sorted(company_detail_list, key=lambda x: x['name'], reverse=True)]
sorted_companies

[{'name': 'Company 3'}, {'name': 'Company 2'}, {'name': 'Company 1'}]

In [4]:
for company in company_detail_list:
    print(f"{company['name']}: {company['domain']} ({company['country']})")

Company 1: Retail (United States)
Company 2: Technology (United Kingdom)
Company 3: Healthcare (United States)

In [10]:
# Company and employee data
company_detail_list = [
    {'name': 'Company 1', 'domain': 'Retail', 'country': 'United States'},
    {'name': 'Company 2', 'domain': 'Technology', 'country': 'United Kingdom'},
    {'name': 'Company 3', 'domain': 'Healthcare', 'country': 'United States'}
]

employee_detail_list = [
    {'name': 'EMP-0001', 'first_name': 'John', 'last_name': 'Doe', 'full_name': 'John Doe', 'company': 'Company 1', 'nationality': 'Australia'},
    {'name': 'EMP-0002', 'first_name': 'Tom', 'last_name': 'Smith', 'full_name': 'Tom Smith', 'company': 'Company 2', 'nationality': 'United States'},
    {'name': 'EMP-0003', 'first_name': 'Andrew', 'last_name': 'Sebastian', 'full_name': 'Andrew Sebastian', 'company': 'Company 3', 'nationality': 'United States'},
    {'name': 'EMP-0005', 'first_name': 'Ying Han', 'last_name': 'Tan', 'full_name': 'Ying Han Tan', 'company': 'Company 1', 'nationality': 'Australia'},
    {'name': 'EMP-0015', 'first_name': 'Kenneth', 'last_name': 'Ng', 'full_name': 'Kenneth Ng', 'company': 'Company 3', 'nationality': 'United States'},
    {'name': 'EMP-0018', 'first_name': 'Rubby', 'last_name': 'Lee', 'full_name': 'Rubby Lee', 'company': 'Company 2', 'nationality': 'Hong Kong'},
    {'name': 'EMP-0017', 'first_name': 'Robert', 'last_name': 'White', 'full_name': 'Robert White', 'company': 'Company 1', 'nationality': 'United Kingdom'}
]

# Create a mapping of company name to domain
company_to_domain = {company['name']: company['domain'] for company in company_detail_list}

# Organize employees by company domain
employees_by_domain = {}
for employee in employee_detail_list:
    domain = company_to_domain.get(employee['company'])
    if domain:
        if domain not in employees_by_domain:
            employees_by_domain[domain] = []
        employees_by_domain[domain].append(employee['full_name'])

# Display result
print(employees_by_domain)

{'Retail': ['John Doe', 'Ying Han Tan', 'Robert White'], 'Technology': ['Tom Smith', 'Rubby Lee'], 'Healthcare': ['Andrew Sebastian', 'Kenneth Ng']}

In [11]:
# Let's create a function to match each employee with the country of their associated company.

company_detail_list = [
    {
        'name': 'Company 1',
        'domain': 'Retail',
        'country': 'United States'
    },
    {
        'name': 'Company 2',
        'domain': 'Technology',
        'country': 'United Kingdom'
    },
    {
        'name': 'Company 3',
        'domain': 'Healthcare',
        'country': 'United States'
    }
]

employee_detail_list = [
    {
        'name': 'EMP-0001',
        'first_name': 'John',
        'last_name': 'Doe',
        'full_name': 'John Doe',
        'company': 'Company 1',
        'nationality': 'Australia'
    },
    {
        'name': 'EMP-0002',
        'first_name': 'Tom',
        'last_name': 'Smith',
        'full_name': 'Tom Smith',
        'company': 'Company 2',
        'nationality': 'United States'
    },
    {
        'name': 'EMP-0003',
        'first_name': 'Andrew',
        'last_name': 'Sebastian',
        'full_name': 'Andrew Sebastian',
        'company': 'Company 3',
        'nationality': 'United States'
    },
    {
        'name': 'EMP-0005',
        'first_name': 'Ying Han',
        'last_name': 'Tan',
        'full_name': 'Ying Han Tan',
        'company': 'Company 1',
        'nationality': 'Australia'
    },
    {
        'name': 'EMP-0015',
        'first_name': 'Kenneth',
        'last_name': 'Ng',
        'full_name': 'Kenneth Ng',
        'company': 'Company 3',
        'nationality': 'United States'
    },
    {
        'name': 'EMP-0018',
        'first_name': 'Rubby',
        'last_name': 'Lee',
        'full_name': 'Rubby Lee',
        'company': 'Company 2',
        'nationality': 'Hong Kong'
    },
    {
        'name': 'EMP-0017',
        'first_name': 'Robert',
        'last_name': 'White',
        'full_name': 'Robert White',
        'company': 'Company 1',
        'nationality': 'United Kingdom'
    }
]

def get_employees_with_company_country(employee_list, company_list):
    # Create a dictionary mapping company names to their respective countries
    company_country_map = {company['name']: company['country'] for company in company_list}
    
    # Create a list of employees with their associated company country
    result = [
        {
            "full_name": employee["full_name"],
            "company": employee["company"],
            "country": company_country_map.get(employee["company"], "Unknown")
        }
        for employee in employee_list
    ]
    
    return result

# Execute the function
get_employees_with_company_country(employee_detail_list, company_detail_list)

[{'full_name': 'John Doe', 'company': 'Company 1', 'country': 'United States'},
 {'full_name': 'Tom Smith',
  'company': 'Company 2',
  'country': 'United Kingdom'},
 {'full_name': 'Andrew Sebastian',
  'company': 'Company 3',
  'country': 'United States'},
 {'full_name': 'Ying Han Tan',
  'company': 'Company 1',
  'country': 'United States'},
 {'full_name': 'Kenneth Ng',
  'company': 'Company 3',
  'country': 'United States'},
 {'full_name': 'Rubby Lee',
  'company': 'Company 2',
  'country': 'United Kingdom'},
 {'full_name': 'Robert White',
  'company': 'Company 1',
  'country': 'United States'}]

In [12]:
from collections import defaultdict

company_detail_list = [
    {
        'name': 'Company 1',
        'domain': 'Retail',
        'country': 'United States'
    },
    {
        'name': 'Company 2',
        'domain': 'Technology',
        'country': 'United Kingdom'
    },
    {
        'name': 'Company 3',
        'domain': 'Healthcare',
        'country': 'United States'
    }
]

employee_detail_list = [
    {
        'name': 'EMP-0001',
        'first_name': 'John',
        'last_name': 'Doe',
        'full_name': 'John Doe',
        'company': 'Company 1',
        'nationality': 'Australia'
    },
    {
        'name': 'EMP-0002',
        'first_name': 'Tom',
        'last_name': 'Smith',
        'full_name': 'Tom Smith',
        'company': 'Company 2',
        'nationality': 'United States'
    },
    {
        'name': 'EMP-0003',
        'first_name': 'Andrew',
        'last_name': 'Sebastian',
        'full_name': 'Andrew Sebastian',
        'company': 'Company 3',
        'nationality': 'United States'
    },
    {
        'name': 'EMP-0005',
        'first_name': 'Ying Han',
        'last_name': 'Tan',
        'full_name': 'Ying Han Tan',
        'company': 'Company 1',
        'nationality': 'Australia'
    },
    {
        'name': 'EMP-0015',
        'first_name': 'Kenneth',
        'last_name': 'Ng',
        'full_name': 'Kenneth Ng',
        'company': 'Company 3',
        'nationality': 'United States'
    },
    {
        'name': 'EMP-0018',
        'first_name': 'Rubby',
        'last_name': 'Lee',
        'full_name': 'Rubby Lee',
        'company': 'Company 2',
        'nationality': 'Hong Kong'
    },
    {
        'name': 'EMP-0017',
        'first_name': 'Robert',
        'last_name': 'White',
        'full_name': 'Robert White',
        'company': 'Company 1',
        'nationality': 'United Kingdom'
    }
]

def get_company_nationality_count(company_detail_list, employee_detail_list):
    # Dictionary to store the nationality count for each company
    company_nationality_count = defaultdict(lambda: defaultdict(int))

    # Counting employee nationalities per company
    for employee in employee_detail_list:
        company_name = employee['company']
        nationality = employee['nationality']
        company_nationality_count[company_name][nationality] += 1

    # Formatting the result as requested
    result = []
    for company in company_detail_list:
        company_name = company['name']
        result.append({
            "company": company_name,
            "employee_nationality": dict(company_nationality_count[company_name])
        })

    return result

# Running the function
get_company_nationality_count(company_detail_list, employee_detail_list)

[{'company': 'Company 1',
  'employee_nationality': {'Australia': 2, 'United Kingdom': 1}},
 {'company': 'Company 2',
  'employee_nationality': {'United States': 1, 'Hong Kong': 1}},
 {'company': 'Company 3', 'employee_nationality': {'United States': 2}}]